Repository DIT113-V22/group-01, pull requests merged in 2022-04, with the labels that each got.

#17 #3 Create mqtt topic specification
  .github/workflows/arduino-build.yml
  .vscode/c_cpp_properties.json
  .vscode/settings.json
  SmartCarMQTTApp/.gitignore
  SmartCarMQTTApp/app/.gitignore
  SmartCarMQTTApp/app/build.gradle
  SmartCarMQTTApp/app/proguard-rules.pro
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/ExampleInstrumentedTest.java
  SmartCarMQTTApp/app/src/main/AndroidManifest.xml
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MQTTFacade.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MainActivity.java
  SmartCarMQTTApp/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  SmartCarMQTTApp/app/src/main/res/drawable/ic_launcher_background.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_main.xml
  SmartCarMQTTApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  SmartCarMQTTApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  SmartCarMQTTApp/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  SmartCarMQTTApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  SmartCarMQTTApp/app/src/main/res/values-night/themes.xml
  SmartCarMQTTApp/app/src/main/res/values/colors.xml
  SmartCarMQTTApp/app/src/main/res/values/strings.xml
  SmartCarMQTTApp/app/src/main/res/values/themes.xml
  SmartCarMQTTApp/app/src/test/java/com/example/smartcarmqttapp/ExampleUnitTest.java
  SmartCarMQTTApp/build.gradle
  SmartCarMQTTApp/gradle.properties
  SmartCarMQTTApp/gradle/wrapper/gradle-wrapper.jar
  SmartCarMQTTApp/gradle/wrapper/gradle-wrapper.properties
  SmartCarMQTTApp/gradlew
  SmartCarMQTTApp/gradlew.bat
  SmartCarMQTTApp/settings.gradle
  arduino/smartcar/smartcar.ino
Labels: documentation, enhancement

#21 #20 Provide a test environment
  .github/workflows/android-build.yml
  README.md
  SmartCarMQTTApp/app/build.gradle
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/ExampleInstrumentedTest.java
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/IntegrationTestUtils.java
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/MqttCarTest.java
  SmartCarMQTTApp/app/src/main/AndroidManifest.xml
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MQTTFacade.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MainActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MqttCar.java
  SmartCarMQTTApp/app/src/test/java/com/example/smartcarmqttapp/ExampleUnitTest.java
  SmartCarMQTTApp/gradlew
  arduino/smartcar/smartcar.ino
Labels: enhancement, Sprint #1

#23 #11 Add app colour and app icon
  .gitignore
  SmartCarMQTTApp/app/build.gradle
  SmartCarMQTTApp/app/src/main/AndroidManifest.xml
  SmartCarMQTTApp/app/src/main/ic_launcher-playstore.png
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/HomeActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MainActivity.java
  SmartCarMQTTApp/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  SmartCarMQTTApp/app/src/main/res/drawable-v24/signal_logo.png
  SmartCarMQTTApp/app/src/main/res/drawable/ic_baseline_menu_24.xml
  SmartCarMQTTApp/app/src/main/res/drawable/ic_launcher_background.xml
  SmartCarMQTTApp/app/src/main/res/drawable/ic_launcher_foreground.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_home.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_main.xml
  SmartCarMQTTApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  SmartCarMQTTApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  SmartCarMQTTApp/app/src/main/res/values-night/themes.xml
  SmartCarMQTTApp/app/src/main/res/values/colors.xml
  SmartCarMQTTApp/app/src/main/res/values/ic_launcher_background.xml
  SmartCarMQTTApp/app/src/main/res/values/themes.xml
Labels: enhancement, Sprint #1

#26 4 Initialize sensors and publish their data
  .gitignore
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/MqttCarTest.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/HomeActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MainActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MqttCar.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_home.xml
  arduino/smartcar/smartcar.ino
Labels: enhancement

#27 6 Add emergency stop to the car
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/MqttCarTest.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MqttCar.java
  arduino/smartcar/smartcar.ino
Labels: enhancement

#28 7 Add steering to the car
  .DS_Store
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/MqttCarTest.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MqttCar.java
  arduino/smartcar/smartcar.ino
Labels: enhancement

#29 Milestone 1 tests development
  .DS_Store
  .gitignore
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/MqttCarTest.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/HomeActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MainActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MqttCar.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_home.xml
  arduino/smartcar/smartcar.ino
Labels: enhancement
