Repository DIT113-V22/group-01, pull requests merged in 2022-05, with the labels that each got.

#55 41 implement the quiz timer
  SmartCarMQTTApp/app/src/main/AndroidManifest.xml
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/QuizResultActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/TimerActivity.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_result.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_timer.xml
  SmartCarMQTTApp/app/src/main/res/layout/timer_dialog.xml
Labels: enhancement, Sprint #2

#56 34 implement quiz state management
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/CrushersDataBase.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/CrushersDataBaseManager.java
Labels: enhancement, Sprint #2

#57 37 create quiz UI
  SmartCarMQTTApp/app/src/main/AndroidManifest.xml
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/PracticeDrivingActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/PracticeTheoryActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/QuizQuestionActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/QuizResultActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/state/QuizState.java
  SmartCarMQTTApp/app/src/main/res/drawable/button_border.xml
  SmartCarMQTTApp/app/src/main/res/drawable/correct_border.xml
  SmartCarMQTTApp/app/src/main/res/drawable/ic_baseline_follow_the_signs_24.xml
  SmartCarMQTTApp/app/src/main/res/drawable/ic_baseline_timer_off_24.xml
  SmartCarMQTTApp/app/src/main/res/drawable/progressbar_circle.xml
  SmartCarMQTTApp/app/src/main/res/drawable/wrong_border.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_connect_car.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_practice_theory.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_question.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_result.xml
  SmartCarMQTTApp/app/src/main/res/layout/explanation_dialog.xml
  SmartCarMQTTApp/app/src/main/res/layout/settings_dialog.xml
Labels: enhancement, Sprint #2

#58 39 update the quiz state
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/CrushersDataBase.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/CrushersDataBaseManager.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/PracticeTheoryActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/QuizQuestionActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/Result.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/state/QuizState.java
  SmartCarMQTTApp/app/src/main/res/layout/settings_dialog.xml
Labels: enhancement, Sprint #2

#59 43 add dashboard to the practice driving screen
  SmartCarMQTTApp/app/build.gradle
  SmartCarMQTTApp/app/src/main/AndroidManifest.xml
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/AboutUsActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/ConnectedCarActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/HomeActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MainActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MqttCar.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/Navigation.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/database/CrushersDataBase.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/database/CrushersDataBaseManager.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/database/QuizContract.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Question.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Result.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/AboutUsActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/ConnectedCarActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/HomeActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/PracticeDrivingActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/PracticeTheoryActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/QuizQuestionActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/QuizResultActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/TimerActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/state/QuizState.java
  SmartCarMQTTApp/app/src/main/res/anim/blinker.xml
  SmartCarMQTTApp/app/src/main/res/drawable-anydpi/ic_arrow.xml
  SmartCarMQTTApp/app/src/main/res/drawable-anydpi/ic_arrow_down.xml
  SmartCarMQTTApp/app/src/main/res/drawable-anydpi/ic_arrow_left.xml
  SmartCarMQTTApp/app/src/main/res/drawable-anydpi/ic_arrow_right.xml
  SmartCarMQTTApp/app/src/main/res/drawable-anydpi/ic_blinker.xml
  SmartCarMQTTApp/app/src/main/res/drawable-hdpi/ic_arrow.png
  SmartCarMQTTApp/app/src/main/res/drawable-hdpi/ic_arrow_down.png
  SmartCarMQTTApp/app/src/main/res/drawable-hdpi/ic_arrow_left.png
  SmartCarMQTTApp/app/src/main/res/drawable-hdpi/ic_arrow_right.png
  SmartCarMQTTApp/app/src/main/res/drawable-hdpi/ic_blinker.png
  SmartCarMQTTApp/app/src/main/res/drawable-mdpi/ic_arrow.png
  SmartCarMQTTApp/app/src/main/res/drawable-mdpi/ic_arrow_down.png
  SmartCarMQTTApp/app/src/main/res/drawable-mdpi/ic_arrow_left.png
  SmartCarMQTTApp/app/src/main/res/drawable-mdpi/ic_arrow_right.png
  SmartCarMQTTApp/app/src/main/res/drawable-mdpi/ic_blinker.png
  SmartCarMQTTApp/app/src/main/res/drawable-xhdpi/ic_arrow.png
  SmartCarMQTTApp/app/src/main/res/drawable-xhdpi/ic_arrow_down.png
  SmartCarMQTTApp/app/src/main/res/drawable-xhdpi/ic_arrow_left.png
  SmartCarMQTTApp/app/src/main/res/drawable-xhdpi/ic_arrow_right.png
  SmartCarMQTTApp/app/src/main/res/drawable-xhdpi/ic_blinker.png
  SmartCarMQTTApp/app/src/main/res/drawable-xxhdpi/ic_arrow.png
  SmartCarMQTTApp/app/src/main/res/drawable-xxhdpi/ic_arrow_down.png
  SmartCarMQTTApp/app/src/main/res/drawable-xxhdpi/ic_arrow_left.png
  SmartCarMQTTApp/app/src/main/res/drawable-xxhdpi/ic_arrow_right.png
  SmartCarMQTTApp/app/src/main/res/drawable-xxhdpi/ic_blinker.png
  SmartCarMQTTApp/app/src/main/res/layout/activity_about_us.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_connect_car.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_home.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_practice_driving.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_practice_theory.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_question.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_result.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_timer.xml
  arduino/smartcar/smartcar.ino
  mosquitto.conf
Labels: enhancement, Sprint #2

#60 40 add review category management
  SmartCarMQTTApp/app/build.gradle
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/state/QuizState.java
Labels: Sprint #2

#62 45 add optional tilting for steering
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/Navigation.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/ConnectedCarActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/HomeActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/PracticeDrivingActivity.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_about_us.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_practice_driving.xml
Labels: enhancement, Sprint #2

#63 35 gather quiz questions
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/database/CrushersDataBase.java
Labels: Sprint #2

#64 Add Controls to Practice Driving
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MqttCar.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/PracticeDrivingActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/PracticeTheoryActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/QuizQuestionActivity.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_aboutus.xml
  SmartCarMQTTApp/app/src/main/res/layout/theory_section.xml
Labels: Sprint #2

#73 Clean up Quiz UI
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/database/CrushersDataBase.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/PracticeTheoryActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/QuizQuestionActivity.java
  SmartCarMQTTApp/app/src/main/res/drawable/exam_logo.png
  SmartCarMQTTApp/app/src/main/res/drawable/quiz_logo.png
  SmartCarMQTTApp/app/src/main/res/drawable/review_logo.png
  SmartCarMQTTApp/app/src/main/res/layout/activity_aboutus.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_connect_car.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_question.xml
  SmartCarMQTTApp/app/src/main/res/layout/row.xml
  SmartCarMQTTApp/app/src/main/res/layout/theory_section.xml
Labels: enhancement, Sprint #2

#74 69 control animation playback
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/QuizQuestionActivity.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_question.xml
Labels: enhancement, Sprint #3

#76 68 create and add question illustrations
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/database/CrushersDataBase.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/database/QuizContract.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Question.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/QuizQuestionActivity.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_question.xml
  SmartCarMQTTApp/app/src/main/res/raw/t1q1.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q10.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q11.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q12.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q13.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q14.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q15.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q2.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q3.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q4.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q5.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q6.png
  SmartCarMQTTApp/app/src/main/res/raw/t1q7.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t1q8.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t1q9.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t2q1.png
  SmartCarMQTTApp/app/src/main/res/raw/t2q10.png
  SmartCarMQTTApp/app/src/main/res/raw/t2q11.png
  SmartCarMQTTApp/app/src/main/res/raw/t2q12.png
  SmartCarMQTTApp/app/src/main/res/raw/t2q13.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t2q14.png
  SmartCarMQTTApp/app/src/main/res/raw/t2q15.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t2q2.png
  SmartCarMQTTApp/app/src/main/res/raw/t2q3.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t2q4.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t2q5.png
  SmartCarMQTTApp/app/src/main/res/raw/t2q6.png
  SmartCarMQTTApp/app/src/main/res/raw/t2q7.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t2q8.webp
  SmartCarMQTTApp/app/src/main/res/raw/t2q9.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q1.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q10.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q11.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t3q12.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q13.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q14.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q15.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q2.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q3.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q4.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q5.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t3q6.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q7.jpeg
  SmartCarMQTTApp/app/src/main/res/raw/t3q8.png
  SmartCarMQTTApp/app/src/main/res/raw/t3q9.jpeg
Labels: enhancement, Sprint #3

#75 71 tests for the practice theory screen quizquestion screen
  SmartCarMQTTApp/app/build.gradle
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/MainActivityTest.java
Labels: enhancement, Sprint #3

#85 82 add unit tests for quiz logic
  .github/workflows/android-build.yml
  SmartCarMQTTApp/app/build.gradle
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/database/CrushersDataBase.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Question.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/PracticeTheoryActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/quiz/QuizQuestionActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/state/QuizState.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_practice_theory.xml
  SmartCarMQTTApp/app/src/test/java/com/example/smartcarmqttapp/QuizUnitTest.java
Labels: enhancement, Sprint #4

#86 84 Add bug fixes
  .github/workflows/android-build.yml
  .vscode/arduino.json
  .vscode/c_cpp_properties.json
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/InstrumentedTest.java
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/MainActivityTest.java
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/MqttCarTest.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/MqttCar.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/AudioPlayer.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/PracticeDrivingActivity.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/state/QuizState.java
  SmartCarMQTTApp/app/src/main/res/anim/blinker.xml
  SmartCarMQTTApp/app/src/main/res/drawable/gradient4.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_practice_driving.xml
  SmartCarMQTTApp/app/src/main/res/layout/activity_quiz_question.xml
  SmartCarMQTTApp/app/src/main/res/raw/blinker.mp3
  SmartCarMQTTApp/app/src/main/res/values/colors.xml
  emulator/lindholmen/default_env.tres
  emulator/lindholmen/environments/lindholmen.gd
Labels: Sprint #4

#88 80 add joystick for controlling the car
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/JoystickView.java
  SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/screens/PracticeDrivingActivity.java
  SmartCarMQTTApp/app/src/main/res/layout/activity_practice_driving.xml
Labels: enhancement, Sprint #4

#89 83 update wiki
  README.md
  SmartCarMQTTApp/app/src/androidTest/java/com/example/smartcarmqttapp/InstrumentedTest.java
Labels: enhancement, Sprint #4
